### ISSUE TITLE
Add a toggle to show only published releases in the past releases list.

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-release-coordinator#110]
https://kf-ui-release-coordinator.kidsfirstdrc.org/releases has a bunch of things that never got released in it, but I need to compare the things that actually made it to the portal.

If I sort the table by "State", two unhelpful things happen:

1. The published ones are buried by staged ones.
2. They aren't shown in creation order.

If I could see only the published ones, then I could sort by date and it would show what I need.

**Comment by dankolbman** [comment]
Thanks for the issue.
Looks like this functionality was lost when I replaced the tables with a different library. Will look into how to filter by state using the new one.

**Comment by rosibaj** [comment]
@dankolbman this is also inaccurate due to the issues that the ETL publishing and the release being failed are two different states --> for example, the past 3 releases are failed bc one service didn't publish, but those actually made it to the portal.

**Comment by dankolbman** [comment]
@rosibaj this does seem accurate according to the [current state flow](https://github.com/kids-first/kf-api-release-coordinator#modes-of-failure-and-cancelation) in the release coordinator, although we didn't strongly define what should happen in this case.
In my mind, this does make sense, as all task services are equal, so if one task fails, the release fails and all tasks in that release are told to cancel the release.
