### ISSUE TITLE
netlify login links busted

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-ui-release-coordinator#113]
<img width="857" alt="screen shot 2019-02-11 at 3 32 25 pm" src="https://user-images.githubusercontent.com/201996/52591555-3da4a480-2e12-11e9-86c3-dd30f5eb26f5.png">

**Comment by dankolbman** [comment]
Unfortunately, there's nothing we can do about this as you cannot specify redirects for wildcard subdomains. Will have too look at the QA deployment instead.
