### ISSUE TITLE
Date on release page always shows current time

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-release-coordinator#137]
There is a problem where the `Created At` date always displays the current time on the release page, rather than it's true created at time.

### Release page
<img width="495" alt="Screen Shot 2019-04-22 at 4 36 00 PM" src="https://user-images.githubusercontent.com/2495894/56528268-e2331900-651c-11e9-8bb3-964ce451b351.png">

### Actual creation time
<img width="231" alt="Screen Shot 2019-04-22 at 4 36 07 PM" src="https://user-images.githubusercontent.com/2495894/56528295-ecedae00-651c-11e9-9d57-24f8580e0e76.png">

**Comment by aalex** [comment]
if you go to https://kf-ui-release-coordinator.kidsfirstdrc.org/studies/SD_46SK55A3 it seems like all the dates for each release are the same.

![screenshot_2019-04-30_11-16-44_kf-ui-release-coordinator_dates_bug](https://user-images.githubusercontent.com/293677/56974534-099d6d80-6b3d-11e9-9633-b37f2f212155.png)

**Comment by dankolbman** [comment]
Fixed in #139
