### ISSUE TITLE
Planner Page

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-ui-release-coordinator#75]
page layout shouldn't be wrapped in a card

- move the `this is a major release` to the top as that's an important item that needs to be made more prevelant, could be a toggle 

Studies section: study id tags could reflect the status of that study 

Services to be run for this release could follow the same recommendations as #74 

`Start Release` button could be aligned right. Right now it competes for attention with the Status indicator which is a separate thing than the actions that are available to take on the new release that was just created

**Comment by dankolbman** [comment]
Taken care of with #51
