### ISSUE TITLE
Release Detail Page: Release Meta info

### ISSUE THREAD

**Issue by bdolly** [kids-first/kf-ui-release-coordinator#77]
Page shouldn't be wrapped in a card component. Cards are reserved for dashboard components. 
<img width="905" alt="screen shot 2018-10-18 at 11 36 01 am" src="https://user-images.githubusercontent.com/1334131/47166398-19084800-d2ca-11e8-9dbd-9d83bfc381f4.png">
Seems like some of the info is repeated `Tests Reports`. The second  instance of it is a larger font size and it's position make it seem like it would be a description but there's a notes section further down. 

The tags with the icon could be right aligned  with the main title to condense space and allow you to move the rest of the info up. 

Created at and author could be on the same line. Not sure if all that timestamp info is necessary, if so you can just truncate the text when the screen size squishes it so it doesn't break the layout. 

Study id tags should be color coded to the status of the study and link to the study.

**Comment by dankolbman** [comment]
Release pages were cleaned up a lot in #51
